GET http://localhost:3000/login

###

GET  http://localhost:3000/login/devTest@gmail.com/passwd

###

POST  http://localhost:3000/register
Content-Type: application/json

{
   "email": "devTest@gmail.com",
   "passwd": "passwd",
   "userType": "ADMIN"
}